Update workflow.yml

diff --git a/.github/workflow/workflow.yml b/.github/workflow/workflow.yml
--- a/.github/workflow/workflow.yml
+++ b/.github/workflow/workflow.yml
@@ -8,15 +8,16 @@ on:
     branches: [ master ]
 
 jobs:
-  # Build jobbuild:
-  name: My First Pipeline
-  # Run on Ubuntu using the latest version
-  runs-on: ubuntu-latest
-  # Job's steps
-  steps:
-    # Check-out your repository
-    - uses: actions/checkout@v3
-    - name: To Show Error
-      run: echo "Should fail at this point ..." ; exit 1
-    - name: Run a one-line script
-      run: echo "Continuous Integration"
+  # Build job
+  build:
+    name: My First Pipeline
+    # Run on Ubuntu using the latest version
+    runs-on: ubuntu-latest
+    # Job's steps
+    steps:
+      # Check-out your repository
+      - uses: actions/checkout@v3
+      - name: To Show Error
+        run: echo "Should fail at this point ..." ; exit 1
+      - name: Run a one-line script
+        run: echo "Continuous Integration"
